baseURL: "https://blog.bussonline.de"
languageCode: "de-DE"
title: "Blog | Thomas Buß"
enableRobotsTXT: true

permalinks:
  blog: "/blog/:slug/"

params:
  description: "Blog von Thomas Buß – Cybersecurity, Data Protection und die Liebe fürs Web"
  author: "Thomas Buß"